### ISSUE TITLE
Mejorar estilo de footer

### ISSUE THREAD

**Issue by naysolange** [nportas/poroteo-senado#4]

**Comment by naysolange** [comment]
tal vez se puede probar achicar las imágenes de ecofeminita y activá el congreso que estén encima de "hecho por las de sistemas"

**Comment by Ana-Belen** [comment]
Si, eso seguro va a mejorar. Por otro lado, en activa el congreso tienen una versión sintetizada y vertical de su logo para el footer su propio site, que tambien usan en su perfil de redes sociales. 
Te pasaron alguna indicación de cómo se usa ese logo? Tengo la sensación de que estamos usando el logo de sus headers, que está diseñado para ser enorme y por eso desbalancea tanto. 

Este es el que tienen en su footer
![screen shot 2018-07-11 at 14 18 28](https://user-images.githubusercontent.com/10106996/42588935-aeff8c2c-8515-11e8-8af6-6cb86fd332ee.png)
